class ConditionsPDE():
    def currentCheckedComboBoxItemConditions(section, comb):
        for i in range(section.count()):
            section.widget(i).hide()
            section.setItemEnabled(i, False)

        if comb.currentIndex() == 2:
            section.setItemEnabled(comb.currentIndex(), True)
            section.setItemEnabled(comb.currentIndex() + 1, True)
            section.widget(comb.currentIndex()).show()
            section.widget(comb.currentIndex() + 1).show()
        elif comb.currentIndex() == 3:
            section.setItemEnabled(comb.currentIndex()+1, True)
            section.widget(comb.currentIndex() + 1).show()
        else:
            section.setItemEnabled(comb.currentIndex(), True)
            section.widget(comb.currentIndex()).show()

    def currentRowDiffusionCoef(currentIndexRow, currentIndexColumn, diffusionCoefElements):
        # diffusionCoefElements[1].setEnabled(False)

        if (currentIndexRow == 0 and currentIndexColumn == 0):
            diffusionCoefElements[1].setEnabled(False)
            diffusionCoefElements[2].setEnabled(False)
            diffusionCoefElements[3].setEnabled(False)
            diffusionCoefElements[4].setEnabled(False)
            diffusionCoefElements[5].setEnabled(False)
            diffusionCoefElements[6].setEnabled(False)
            diffusionCoefElements[7].setEnabled(False)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 0 and currentIndexColumn == 1):
            diffusionCoefElements[1].setEnabled(True)
            diffusionCoefElements[2].setEnabled(False)
            diffusionCoefElements[3].setEnabled(False)
            diffusionCoefElements[4].setEnabled(False)
            diffusionCoefElements[5].setEnabled(False)
            diffusionCoefElements[6].setEnabled(False)
            diffusionCoefElements[7].setEnabled(False)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 0 and currentIndexColumn == 2):
            diffusionCoefElements[1].setEnabled(True)
            diffusionCoefElements[2].setEnabled(True)
            diffusionCoefElements[3].setEnabled(False)
            diffusionCoefElements[4].setEnabled(False)
            diffusionCoefElements[5].setEnabled(False)
            diffusionCoefElements[6].setEnabled(False)
            diffusionCoefElements[7].setEnabled(False)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 1 and currentIndexColumn == 0):
            diffusionCoefElements[1].setEnabled(False)
            diffusionCoefElements[2].setEnabled(False)
            diffusionCoefElements[3].setEnabled(True)
            diffusionCoefElements[4].setEnabled(False)
            diffusionCoefElements[5].setEnabled(False)
            diffusionCoefElements[6].setEnabled(False)
            diffusionCoefElements[7].setEnabled(False)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 1 and currentIndexColumn == 1):
            diffusionCoefElements[1].setEnabled(True)
            diffusionCoefElements[2].setEnabled(False)
            diffusionCoefElements[3].setEnabled(True)
            diffusionCoefElements[4].setEnabled(True)
            diffusionCoefElements[5].setEnabled(False)
            diffusionCoefElements[6].setEnabled(False)
            diffusionCoefElements[7].setEnabled(False)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 1 and currentIndexColumn == 2):
            diffusionCoefElements[1].setEnabled(True)
            diffusionCoefElements[2].setEnabled(True)
            diffusionCoefElements[3].setEnabled(True)
            diffusionCoefElements[4].setEnabled(True)
            diffusionCoefElements[5].setEnabled(True)
            diffusionCoefElements[6].setEnabled(False)
            diffusionCoefElements[7].setEnabled(False)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 2 and currentIndexColumn == 0):
            diffusionCoefElements[1].setEnabled(False)
            diffusionCoefElements[2].setEnabled(False)
            diffusionCoefElements[3].setEnabled(True)
            diffusionCoefElements[4].setEnabled(False)
            diffusionCoefElements[5].setEnabled(False)
            diffusionCoefElements[6].setEnabled(True)
            diffusionCoefElements[7].setEnabled(False)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 2 and currentIndexColumn == 1):
            diffusionCoefElements[1].setEnabled(True)
            diffusionCoefElements[2].setEnabled(False)
            diffusionCoefElements[3].setEnabled(True)
            diffusionCoefElements[4].setEnabled(True)
            diffusionCoefElements[5].setEnabled(False)
            diffusionCoefElements[6].setEnabled(True)
            diffusionCoefElements[7].setEnabled(True)
            diffusionCoefElements[8].setEnabled(False)
        elif (currentIndexRow == 2 and currentIndexColumn == 2):
            diffusionCoefElements[1].setEnabled(True)
            diffusionCoefElements[2].setEnabled(True)
            diffusionCoefElements[3].setEnabled(True)
            diffusionCoefElements[4].setEnabled(True)
            diffusionCoefElements[5].setEnabled(True)
            diffusionCoefElements[6].setEnabled(True)
            diffusionCoefElements[7].setEnabled(True)
            diffusionCoefElements[8].setEnabled(True)