# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Matriz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Matrix(object):
    def setupUi(self, Matrix):
        Matrix.setObjectName("Matrix")
        Matrix.resize(380, 341)
        self.lEditM11 = QtWidgets.QLineEdit(Matrix)
        self.lEditM11.setGeometry(QtCore.QRect(60, 40, 81, 81))
        self.lEditM11.setObjectName("lEditM11")
        self.lEditM12 = QtWidgets.QLineEdit(Matrix)
        self.lEditM12.setGeometry(QtCore.QRect(150, 40, 81, 81))
        self.lEditM12.setObjectName("lEditM12")
        self.lEditM13 = QtWidgets.QLineEdit(Matrix)
        self.lEditM13.setGeometry(QtCore.QRect(240, 40, 81, 81))
        self.lEditM13.setObjectName("lEditM13")
        self.lEditM23 = QtWidgets.QLineEdit(Matrix)
        self.lEditM23.setGeometry(QtCore.QRect(240, 130, 81, 81))
        self.lEditM23.setObjectName("lEditM23")
        self.lEditM21 = QtWidgets.QLineEdit(Matrix)
        self.lEditM21.setGeometry(QtCore.QRect(60, 130, 81, 81))
        self.lEditM21.setObjectName("lEditM21")
        self.lEditM22 = QtWidgets.QLineEdit(Matrix)
        self.lEditM22.setGeometry(QtCore.QRect(150, 130, 81, 81))
        self.lEditM22.setObjectName("lEditM22")
        self.lEditM33 = QtWidgets.QLineEdit(Matrix)
        self.lEditM33.setGeometry(QtCore.QRect(240, 220, 81, 81))
        self.lEditM33.setObjectName("lEditM33")
        self.lEditM31 = QtWidgets.QLineEdit(Matrix)
        self.lEditM31.setGeometry(QtCore.QRect(60, 220, 81, 81))
        self.lEditM31.setObjectName("lEditM31")
        self.lEditM32 = QtWidgets.QLineEdit(Matrix)
        self.lEditM32.setGeometry(QtCore.QRect(150, 220, 81, 81))
        self.lEditM32.setObjectName("lEditM32")

        self.retranslateUi(Matrix)
        QtCore.QMetaObject.connectSlotsByName(Matrix)

    def retranslateUi(self, Matrix):
        _translate = QtCore.QCoreApplication.translate
        Matrix.setWindowTitle(_translate("Matrix", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Matrix = QtWidgets.QDialog()
    ui = Ui_Matrix()
    ui.setupUi(Matrix)
    Matrix.show()
    sys.exit(app.exec_())
